### ISSUE TITLE
min_light & max_light throw an error.

### ISSUE THREAD

**Issue by Neuromancer56** [fluxionary/minetest-spawnit#1]
I added support for this mod in mob_biome_mapper mod, but I noticed that min_light & max_light are throwing an error when used.

**Comment by fluxionary** [comment]
apologies, i renamed those parameters to `max_node_light` and `min_node_light` to contrast w/ `max_natural_light` and `min_natural_light` when i added those.

i still consider this mod WIP - wait until i add it to the content DB before considering any of the API to be stable :) it's close but not there yet.
